#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2LinqClass.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Empresa")]
	public partial class DataEmpresaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertarea(area instance);
    partial void Updatearea(area instance);
    partial void Deletearea(area instance);
    #endregion
		
		public DataEmpresaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EmpresaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEmpresaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<area> area
		{
			get
			{
				return this.GetTable<area>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActulaizarArea")]
		public int ActulaizarArea([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codArea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codArea, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarArea")]
		public ISingleResult<BuscarAreaResult> BuscarArea([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo);
			return ((ISingleResult<BuscarAreaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CrearArea")]
		public int CrearArea([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarArea")]
		public int EliminarArea([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codArea)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codArea);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarArea")]
		public ISingleResult<ListarAreaResult> ListarArea()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarAreaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.area")]
	public partial class area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _areaCod;
		
		private string _areaDes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnareaCodChanging(int value);
    partial void OnareaCodChanged();
    partial void OnareaDesChanging(string value);
    partial void OnareaDesChanged();
    #endregion
		
		public area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaCod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int areaCod
		{
			get
			{
				return this._areaCod;
			}
			set
			{
				if ((this._areaCod != value))
				{
					this.OnareaCodChanging(value);
					this.SendPropertyChanging();
					this._areaCod = value;
					this.SendPropertyChanged("areaCod");
					this.OnareaCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaDes", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string areaDes
		{
			get
			{
				return this._areaDes;
			}
			set
			{
				if ((this._areaDes != value))
				{
					this.OnareaDesChanging(value);
					this.SendPropertyChanging();
					this._areaDes = value;
					this.SendPropertyChanged("areaDes");
					this.OnareaDesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class BuscarAreaResult
	{
		
		private int _areaCod;
		
		private string _areaDes;
		
		public BuscarAreaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaCod", DbType="Int NOT NULL")]
		public int areaCod
		{
			get
			{
				return this._areaCod;
			}
			set
			{
				if ((this._areaCod != value))
				{
					this._areaCod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaDes", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string areaDes
		{
			get
			{
				return this._areaDes;
			}
			set
			{
				if ((this._areaDes != value))
				{
					this._areaDes = value;
				}
			}
		}
	}
	
	public partial class ListarAreaResult
	{
		
		private int _areaCod;
		
		private string _areaDes;
		
		public ListarAreaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaCod", DbType="Int NOT NULL")]
		public int areaCod
		{
			get
			{
				return this._areaCod;
			}
			set
			{
				if ((this._areaCod != value))
				{
					this._areaCod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaDes", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string areaDes
		{
			get
			{
				return this._areaDes;
			}
			set
			{
				if ((this._areaDes != value))
				{
					this._areaDes = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
